services:
  vcv-client:
    container_name: vcv-client
    networks:
      - host-bridge
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile.client
    ports:
      - 51733:5173
    env_file:
      - .env
    develop:
      watch:
        - action: sync
          path: ./apps/client
          target: /usr/src/app/apps/client
          ignore:
            - node_modules
        - action: rebuild
          path: ./apps/client/package.json
    restart: unless-stopped
    depends_on:
      - vcv-server
  vcv-server:
    networks:
      - host-bridge
    container_name: vcv-server
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile.server
    ports:
      - 12923:1209
    develop:
      watch:
        - action: sync
          path: ./apps/server
          target: /usr/src/app/apps/server
          ignore:
            - node_modules
        - action: rebuild
          path: ./apps/server/package.json
    restart: unless-stopped
    depends_on:
      - vcv-db
    env_file:
      - .env
  vcv-db:
    networks:
      - host-bridge
    container_name: vcv-db
    image: postgres:15.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD-password}
    volumes:
      - ~/data/vcv/db:/var/lib/postgresql/data
    ports:
      - 5433:5432

networks:
  host-bridge:
    driver: bridge
