# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: difhack
    steps:
      - uses: actions/checkout@v4
      - run: |
          rm -rf ~/vcv/*
          cp -r ./* ~/vcv/
          cp ~/.env.vcv ~/vcv/.env
          cd ~/syner 
          docker compose down --remove-orphans
          docker compose up -d --build
